joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

diff_drive_controller:
  type: diff_drive_controller/DiffDriveController
  left_wheel:  ['limo$(arg robot_id)/front_left_wheel', 'limo$(arg robot_id)/rear_left_wheel']
  right_wheel: ['limo$(arg robot_id)/front_right_wheel','limo$(arg robot_id)/rear_right_wheel']
  publish_rate: 50
  #set big numbers for unobservable axes (z, roll, pitch) are good (e.g., 1e6) so downstream filters don’t trust them.
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  
  wheel_separation: 0.27
  wheel_radius: 0.049
  cmd_vel_timeout: 0.25
  enable_odom_tf: true

  # Make TF frames unique per robot using launch arg expansion
  odom_frame_id: limo$(arg robot_id)/odom
  base_frame_id: limo$(arg robot_id)/base_link
  
  # Publish final output cmd_vel to /jackal_velocity_controller/cmd_vel_out
  publish_cmd: true



gazebo_ros_control:
  pid_gains:
    limo$(arg robot_id):
      front_left_wheel:  {p: 10.0, i: 0.0, d: 0.1, i_clamp: 1.0}
      rear_left_wheel:   {p: 10.0, i: 0.0, d: 0.1, i_clamp: 1.0}
      front_right_wheel: {p: 10.0, i: 0.0, d: 0.1, i_clamp: 1.0}
      rear_right_wheel:  {p: 10.0, i: 0.0, d: 0.1, i_clamp: 1.0}


